// Copyright © 2025 Prabhjot Singh Sethi, All Rights reserved
// Author: Prabhjot Singh Sethi <prabhjot.sethi@gmail.com>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: logger.proto

package api

import (
	_ "github.com/go-core-stack/grpc-core/coreapis/api"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessLogsGetReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ou under consideration
	Ou string `protobuf:"bytes,1,opt,name=ou,proto3" json:"ou,omitempty"`
	// start timestamp when filter is range
	Start int64 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	// end timestamp when filter is range
	End           int64 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessLogsGetReq) Reset() {
	*x = AccessLogsGetReq{}
	mi := &file_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessLogsGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLogsGetReq) ProtoMessage() {}

func (x *AccessLogsGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLogsGetReq.ProtoReflect.Descriptor instead.
func (*AccessLogsGetReq) Descriptor() ([]byte, []int) {
	return file_logger_proto_rawDescGZIP(), []int{0}
}

func (x *AccessLogsGetReq) GetOu() string {
	if x != nil {
		return x.Ou
	}
	return ""
}

func (x *AccessLogsGetReq) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *AccessLogsGetReq) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type AccessLogItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp of the request (epoch millis or nanos UTC)
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// ou name
	Ou string `protobuf:"bytes,2,opt,name=ou,proto3" json:"ou,omitempty"`
	// User email id
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Unix Timestamp
	RequestTime string `protobuf:"bytes,4,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	// Remote IP address of the requester
	RemoteIp string `protobuf:"bytes,5,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	// http Request
	Method string `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	// Request action, e.g., GET,PUT,LIST
	RequestAction string `protobuf:"bytes,7,opt,name=request_action,json=requestAction,proto3" json:"request_action,omitempty"`
	// url path
	Path string `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
	// HTTP status code for success/failure
	HttpStatusCode string `protobuf:"bytes,9,opt,name=http_status_code,json=httpStatusCode,proto3" json:"http_status_code,omitempty"`
	// The client software making the request
	UserAgent string `protobuf:"bytes,10,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// log level
	Level string `protobuf:"bytes,11,opt,name=level,proto3" json:"level,omitempty"`
	// tenant name
	Tenant        string `protobuf:"bytes,12,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessLogItem) Reset() {
	*x = AccessLogItem{}
	mi := &file_logger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessLogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLogItem) ProtoMessage() {}

func (x *AccessLogItem) ProtoReflect() protoreflect.Message {
	mi := &file_logger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLogItem.ProtoReflect.Descriptor instead.
func (*AccessLogItem) Descriptor() ([]byte, []int) {
	return file_logger_proto_rawDescGZIP(), []int{1}
}

func (x *AccessLogItem) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AccessLogItem) GetOu() string {
	if x != nil {
		return x.Ou
	}
	return ""
}

func (x *AccessLogItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccessLogItem) GetRequestTime() string {
	if x != nil {
		return x.RequestTime
	}
	return ""
}

func (x *AccessLogItem) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *AccessLogItem) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AccessLogItem) GetRequestAction() string {
	if x != nil {
		return x.RequestAction
	}
	return ""
}

func (x *AccessLogItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AccessLogItem) GetHttpStatusCode() string {
	if x != nil {
		return x.HttpStatusCode
	}
	return ""
}

func (x *AccessLogItem) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AccessLogItem) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *AccessLogItem) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type AccessLogsGetResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// list of access log items
	Items         []*AccessLogItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessLogsGetResp) Reset() {
	*x = AccessLogsGetResp{}
	mi := &file_logger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessLogsGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLogsGetResp) ProtoMessage() {}

func (x *AccessLogsGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_logger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLogsGetResp.ProtoReflect.Descriptor instead.
func (*AccessLogsGetResp) Descriptor() ([]byte, []int) {
	return file_logger_proto_rawDescGZIP(), []int{2}
}

func (x *AccessLogsGetResp) GetItems() []*AccessLogItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_logger_proto protoreflect.FileDescriptor

const file_logger_proto_rawDesc = "" +
	"\n" +
	"\flogger.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x17coreapis/api/role.proto\"J\n" +
	"\x10AccessLogsGetReq\x12\x0e\n" +
	"\x02ou\x18\x01 \x01(\tR\x02ou\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x03R\x03end\"\xdd\x02\n" +
	"\rAccessLogItem\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x0e\n" +
	"\x02ou\x18\x02 \x01(\tR\x02ou\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\frequest_time\x18\x04 \x01(\tR\vrequestTime\x12\x1b\n" +
	"\tremote_ip\x18\x05 \x01(\tR\bremoteIp\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12%\n" +
	"\x0erequest_action\x18\a \x01(\tR\rrequestAction\x12\x12\n" +
	"\x04path\x18\b \x01(\tR\x04path\x12(\n" +
	"\x10http_status_code\x18\t \x01(\tR\x0ehttpStatusCode\x12\x1d\n" +
	"\n" +
	"user_agent\x18\n" +
	" \x01(\tR\tuserAgent\x12\x14\n" +
	"\x05level\x18\v \x01(\tR\x05level\x12\x16\n" +
	"\x06tenant\x18\f \x01(\tR\x06tenant\"=\n" +
	"\x11AccessLogsGetResp\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.api.AccessLogItemR\x05items2\x93\x01\n" +
	"\n" +
	"AccessLogs\x12\x84\x01\n" +
	"\rGetAccessLogs\x12\x15.api.AccessLogsGetReq\x1a\x16.api.AccessLogsGetResp\"D\x8a\xb5\x18\x16\n" +
	"\vaccess-logs\x12\x02ou\x1a\x03get\x82\xd3\xe4\x93\x02$\x12\"/api/object-storage/v1/ou/{ou}/logB+Z)github.com/go-core-stack/auth-gateway/apib\x06proto3"

var (
	file_logger_proto_rawDescOnce sync.Once
	file_logger_proto_rawDescData []byte
)

func file_logger_proto_rawDescGZIP() []byte {
	file_logger_proto_rawDescOnce.Do(func() {
		file_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logger_proto_rawDesc), len(file_logger_proto_rawDesc)))
	})
	return file_logger_proto_rawDescData
}

var file_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_logger_proto_goTypes = []any{
	(*AccessLogsGetReq)(nil),  // 0: api.AccessLogsGetReq
	(*AccessLogItem)(nil),     // 1: api.AccessLogItem
	(*AccessLogsGetResp)(nil), // 2: api.AccessLogsGetResp
}
var file_logger_proto_depIdxs = []int32{
	1, // 0: api.AccessLogsGetResp.items:type_name -> api.AccessLogItem
	0, // 1: api.AccessLogs.GetAccessLogs:input_type -> api.AccessLogsGetReq
	2, // 2: api.AccessLogs.GetAccessLogs:output_type -> api.AccessLogsGetResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_logger_proto_init() }
func file_logger_proto_init() {
	if File_logger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logger_proto_rawDesc), len(file_logger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logger_proto_goTypes,
		DependencyIndexes: file_logger_proto_depIdxs,
		MessageInfos:      file_logger_proto_msgTypes,
	}.Build()
	File_logger_proto = out.File
	file_logger_proto_goTypes = nil
	file_logger_proto_depIdxs = nil
}
