// Copyright © 2025 Prabhjot Singh Sethi, All Rights reserved
// Author: Prabhjot Singh Sethi <prabhjot.sethi@gmail.com>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: myaccount.proto

package api

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiKeyDef_Status int32

const (
	// ApiKey is active
	ApiKeyDef_Active ApiKeyDef_Status = 0
	// ApiKey has expired
	ApiKeyDef_Expired ApiKeyDef_Status = 1
	// ApiKey is disabled
	ApiKeyDef_Disabled ApiKeyDef_Status = 2
)

// Enum value maps for ApiKeyDef_Status.
var (
	ApiKeyDef_Status_name = map[int32]string{
		0: "Active",
		1: "Expired",
		2: "Disabled",
	}
	ApiKeyDef_Status_value = map[string]int32{
		"Active":   0,
		"Expired":  1,
		"Disabled": 2,
	}
)

func (x ApiKeyDef_Status) Enum() *ApiKeyDef_Status {
	p := new(ApiKeyDef_Status)
	*p = x
	return p
}

func (x ApiKeyDef_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiKeyDef_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_myaccount_proto_enumTypes[0].Descriptor()
}

func (ApiKeyDef_Status) Type() protoreflect.EnumType {
	return &file_myaccount_proto_enumTypes[0]
}

func (x ApiKeyDef_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiKeyDef_Status.Descriptor instead.
func (ApiKeyDef_Status) EnumDescriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{7, 0}
}

type MyInfoGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyInfoGetReq) Reset() {
	*x = MyInfoGetReq{}
	mi := &file_myaccount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyInfoGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyInfoGetReq) ProtoMessage() {}

func (x *MyInfoGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyInfoGetReq.ProtoReflect.Descriptor instead.
func (*MyInfoGetReq) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{0}
}

type MyInfoGetResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username which is used for login
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// first name of the user
	FirstName string `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	// last name of the user
	LastName string `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	// email of the user
	Email         string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyInfoGetResp) Reset() {
	*x = MyInfoGetResp{}
	mi := &file_myaccount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyInfoGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyInfoGetResp) ProtoMessage() {}

func (x *MyInfoGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyInfoGetResp.ProtoReflect.Descriptor instead.
func (*MyInfoGetResp) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{1}
}

func (x *MyInfoGetResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MyInfoGetResp) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *MyInfoGetResp) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *MyInfoGetResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// my session information
type MySessionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session id
	SessionId string `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	// start time
	Started int64 `protobuf:"varint,2,opt,name=started,proto3" json:"started,omitempty"`
	// last access time
	LastAccess int64 `protobuf:"varint,3,opt,name=lastAccess,proto3" json:"lastAccess,omitempty"`
	// incoming client ip
	Ip string `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	// location information based on IP (optional, omitted for private IPs)
	Loc           *Location `protobuf:"bytes,5,opt,name=loc,proto3,oneof" json:"loc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MySessionInfo) Reset() {
	*x = MySessionInfo{}
	mi := &file_myaccount_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MySessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySessionInfo) ProtoMessage() {}

func (x *MySessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySessionInfo.ProtoReflect.Descriptor instead.
func (*MySessionInfo) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{2}
}

func (x *MySessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MySessionInfo) GetStarted() int64 {
	if x != nil {
		return x.Started
	}
	return 0
}

func (x *MySessionInfo) GetLastAccess() int64 {
	if x != nil {
		return x.LastAccess
	}
	return 0
}

func (x *MySessionInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *MySessionInfo) GetLoc() *Location {
	if x != nil {
		return x.Loc
	}
	return nil
}

// my sessions get response
type MySessionsGetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MySessionInfo       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MySessionsGetResp) Reset() {
	*x = MySessionsGetResp{}
	mi := &file_myaccount_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MySessionsGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySessionsGetResp) ProtoMessage() {}

func (x *MySessionsGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySessionsGetResp.ProtoReflect.Descriptor instead.
func (*MySessionsGetResp) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{3}
}

func (x *MySessionsGetResp) GetItems() []*MySessionInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

// logout session request
type MySessionsLogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MySessionsLogoutReq) Reset() {
	*x = MySessionsLogoutReq{}
	mi := &file_myaccount_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MySessionsLogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySessionsLogoutReq) ProtoMessage() {}

func (x *MySessionsLogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySessionsLogoutReq.ProtoReflect.Descriptor instead.
func (*MySessionsLogoutReq) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{4}
}

func (x *MySessionsLogoutReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// session logout empty response
type MySessionsLogoutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MySessionsLogoutResp) Reset() {
	*x = MySessionsLogoutResp{}
	mi := &file_myaccount_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MySessionsLogoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySessionsLogoutResp) ProtoMessage() {}

func (x *MySessionsLogoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySessionsLogoutResp.ProtoReflect.Descriptor instead.
func (*MySessionsLogoutResp) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{5}
}

type ApiKeyCreateReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key id will be allocated by virtue of key creation
	// user is expected to provide an optional name for
	// ease of reference, it is recommended to be unique
	// but not validated or ensured to be unique
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// validity of the api key, tenure in seconds for
	// which this api key is being created
	// when not set or 0 it means key with no expiry
	Validity      int64 `protobuf:"varint,2,opt,name=validity,proto3" json:"validity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyCreateReq) Reset() {
	*x = ApiKeyCreateReq{}
	mi := &file_myaccount_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyCreateReq) ProtoMessage() {}

func (x *ApiKeyCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyCreateReq.ProtoReflect.Descriptor instead.
func (*ApiKeyCreateReq) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{6}
}

func (x *ApiKeyCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKeyCreateReq) GetValidity() int64 {
	if x != nil {
		return x.Validity
	}
	return 0
}

type ApiKeyDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyDef) Reset() {
	*x = ApiKeyDef{}
	mi := &file_myaccount_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyDef) ProtoMessage() {}

func (x *ApiKeyDef) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyDef.ProtoReflect.Descriptor instead.
func (*ApiKeyDef) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{7}
}

type ApiKeyCreateResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the api key provided by the creator
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// ID of the access key that will be used by the
	// client and server to identify ApiKey in use
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// current status of the Api Key
	Status ApiKeyDef_Status `protobuf:"varint,3,opt,name=status,proto3,enum=api.ApiKeyDef_Status" json:"status,omitempty"`
	// timestamp when the api key was used last time
	LastUsed int64 `protobuf:"varint,4,opt,name=lastUsed,proto3" json:"lastUsed,omitempty"`
	// timestamp when the api key was created
	Created int64 `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	// timestamp when the api key will expire
	ExpireAt int64 `protobuf:"varint,6,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
	// Secret to be used in conjunction with key id
	// for authentication of client using the api key
	// but typically the auth mechanism used will not
	// expect to share this secret ever on the wire
	// after it is being created, neither on APIs nor
	// for authentication
	Secret        string `protobuf:"bytes,7,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyCreateResp) Reset() {
	*x = ApiKeyCreateResp{}
	mi := &file_myaccount_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyCreateResp) ProtoMessage() {}

func (x *ApiKeyCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyCreateResp.ProtoReflect.Descriptor instead.
func (*ApiKeyCreateResp) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{8}
}

func (x *ApiKeyCreateResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKeyCreateResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiKeyCreateResp) GetStatus() ApiKeyDef_Status {
	if x != nil {
		return x.Status
	}
	return ApiKeyDef_Active
}

func (x *ApiKeyCreateResp) GetLastUsed() int64 {
	if x != nil {
		return x.LastUsed
	}
	return 0
}

func (x *ApiKeyCreateResp) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ApiKeyCreateResp) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *ApiKeyCreateResp) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type ApiKeyDisableReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key id that needs to be disabled
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyDisableReq) Reset() {
	*x = ApiKeyDisableReq{}
	mi := &file_myaccount_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyDisableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyDisableReq) ProtoMessage() {}

func (x *ApiKeyDisableReq) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyDisableReq.ProtoReflect.Descriptor instead.
func (*ApiKeyDisableReq) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{9}
}

func (x *ApiKeyDisableReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ApiKeyDisableResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyDisableResp) Reset() {
	*x = ApiKeyDisableResp{}
	mi := &file_myaccount_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyDisableResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyDisableResp) ProtoMessage() {}

func (x *ApiKeyDisableResp) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyDisableResp.ProtoReflect.Descriptor instead.
func (*ApiKeyDisableResp) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{10}
}

type ApiKeyEnableReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key id that needs to be enabled
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyEnableReq) Reset() {
	*x = ApiKeyEnableReq{}
	mi := &file_myaccount_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyEnableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyEnableReq) ProtoMessage() {}

func (x *ApiKeyEnableReq) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyEnableReq.ProtoReflect.Descriptor instead.
func (*ApiKeyEnableReq) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{11}
}

func (x *ApiKeyEnableReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ApiKeyEnableResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyEnableResp) Reset() {
	*x = ApiKeyEnableResp{}
	mi := &file_myaccount_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyEnableResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyEnableResp) ProtoMessage() {}

func (x *ApiKeyEnableResp) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyEnableResp.ProtoReflect.Descriptor instead.
func (*ApiKeyEnableResp) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{12}
}

type ApiKeyDeleteReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key id that needs to be deleted
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyDeleteReq) Reset() {
	*x = ApiKeyDeleteReq{}
	mi := &file_myaccount_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyDeleteReq) ProtoMessage() {}

func (x *ApiKeyDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyDeleteReq.ProtoReflect.Descriptor instead.
func (*ApiKeyDeleteReq) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{13}
}

func (x *ApiKeyDeleteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ApiKeyDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyDeleteResp) Reset() {
	*x = ApiKeyDeleteResp{}
	mi := &file_myaccount_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyDeleteResp) ProtoMessage() {}

func (x *ApiKeyDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyDeleteResp.ProtoReflect.Descriptor instead.
func (*ApiKeyDeleteResp) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{14}
}

type ApiKeysListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeysListReq) Reset() {
	*x = ApiKeysListReq{}
	mi := &file_myaccount_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeysListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeysListReq) ProtoMessage() {}

func (x *ApiKeysListReq) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeysListReq.ProtoReflect.Descriptor instead.
func (*ApiKeysListReq) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{15}
}

type ApiKeyListEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the api key provided by the creator
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// ID of the access key that will be used by the
	// client and server to identify ApiKey in use
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// current status of the Api Key
	Status ApiKeyDef_Status `protobuf:"varint,3,opt,name=status,proto3,enum=api.ApiKeyDef_Status" json:"status,omitempty"`
	// timestamp when the api key was used last time
	LastUsed int64 `protobuf:"varint,4,opt,name=lastUsed,proto3" json:"lastUsed,omitempty"`
	// timestamp when the api key was created
	Created int64 `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	// timestamp when the api key will expire
	ExpireAt      int64 `protobuf:"varint,6,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyListEntry) Reset() {
	*x = ApiKeyListEntry{}
	mi := &file_myaccount_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyListEntry) ProtoMessage() {}

func (x *ApiKeyListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyListEntry.ProtoReflect.Descriptor instead.
func (*ApiKeyListEntry) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{16}
}

func (x *ApiKeyListEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKeyListEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiKeyListEntry) GetStatus() ApiKeyDef_Status {
	if x != nil {
		return x.Status
	}
	return ApiKeyDef_Active
}

func (x *ApiKeyListEntry) GetLastUsed() int64 {
	if x != nil {
		return x.LastUsed
	}
	return 0
}

func (x *ApiKeyListEntry) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ApiKeyListEntry) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type ApiKeysListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ApiKeyListEntry     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeysListResp) Reset() {
	*x = ApiKeysListResp{}
	mi := &file_myaccount_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeysListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeysListResp) ProtoMessage() {}

func (x *ApiKeysListResp) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeysListResp.ProtoReflect.Descriptor instead.
func (*ApiKeysListResp) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{17}
}

func (x *ApiKeysListResp) GetItems() []*ApiKeyListEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

// my sessions get req
type MySessionsGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MySessionsGetReq) Reset() {
	*x = MySessionsGetReq{}
	mi := &file_myaccount_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MySessionsGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySessionsGetReq) ProtoMessage() {}

func (x *MySessionsGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySessionsGetReq.ProtoReflect.Descriptor instead.
func (*MySessionsGetReq) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{18}
}

type MyOrgUnitsListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyOrgUnitsListReq) Reset() {
	*x = MyOrgUnitsListReq{}
	mi := &file_myaccount_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyOrgUnitsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyOrgUnitsListReq) ProtoMessage() {}

func (x *MyOrgUnitsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyOrgUnitsListReq.ProtoReflect.Descriptor instead.
func (*MyOrgUnitsListReq) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{19}
}

type MyOrgUnitEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// org unit id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// org unit display name
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyOrgUnitEntry) Reset() {
	*x = MyOrgUnitEntry{}
	mi := &file_myaccount_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyOrgUnitEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyOrgUnitEntry) ProtoMessage() {}

func (x *MyOrgUnitEntry) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyOrgUnitEntry.ProtoReflect.Descriptor instead.
func (*MyOrgUnitEntry) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{20}
}

func (x *MyOrgUnitEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MyOrgUnitEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MyOrgUnitsListResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// default Org Unit for the user
	Default *MyOrgUnitEntry `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	// list of available org units for user
	// inclusive of default Org unit
	Items         []*MyOrgUnitEntry `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyOrgUnitsListResp) Reset() {
	*x = MyOrgUnitsListResp{}
	mi := &file_myaccount_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyOrgUnitsListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyOrgUnitsListResp) ProtoMessage() {}

func (x *MyOrgUnitsListResp) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyOrgUnitsListResp.ProtoReflect.Descriptor instead.
func (*MyOrgUnitsListResp) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{21}
}

func (x *MyOrgUnitsListResp) GetDefault() *MyOrgUnitEntry {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *MyOrgUnitsListResp) GetItems() []*MyOrgUnitEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

type DefaultOrgUnitReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the Org Unit to be set as default
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultOrgUnitReq) Reset() {
	*x = DefaultOrgUnitReq{}
	mi := &file_myaccount_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultOrgUnitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultOrgUnitReq) ProtoMessage() {}

func (x *DefaultOrgUnitReq) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultOrgUnitReq.ProtoReflect.Descriptor instead.
func (*DefaultOrgUnitReq) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{22}
}

func (x *DefaultOrgUnitReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DefaultOrgUnitResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultOrgUnitResp) Reset() {
	*x = DefaultOrgUnitResp{}
	mi := &file_myaccount_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultOrgUnitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultOrgUnitResp) ProtoMessage() {}

func (x *DefaultOrgUnitResp) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultOrgUnitResp.ProtoReflect.Descriptor instead.
func (*DefaultOrgUnitResp) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{23}
}

type MyRegionsListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyRegionsListReq) Reset() {
	*x = MyRegionsListReq{}
	mi := &file_myaccount_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyRegionsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyRegionsListReq) ProtoMessage() {}

func (x *MyRegionsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyRegionsListReq.ProtoReflect.Descriptor instead.
func (*MyRegionsListReq) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{24}
}

type MyRegionsListEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// identifier of the region
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name of the region typically unique for tenant
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyRegionsListEntry) Reset() {
	*x = MyRegionsListEntry{}
	mi := &file_myaccount_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyRegionsListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyRegionsListEntry) ProtoMessage() {}

func (x *MyRegionsListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyRegionsListEntry.ProtoReflect.Descriptor instead.
func (*MyRegionsListEntry) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{25}
}

func (x *MyRegionsListEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MyRegionsListEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MyRegionsListResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// default region for the user
	Default *MyRegionsListEntry `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	// list of available regions for the tenant
	// inclusive of the set default region
	Items         []*MyRegionsListEntry `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyRegionsListResp) Reset() {
	*x = MyRegionsListResp{}
	mi := &file_myaccount_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyRegionsListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyRegionsListResp) ProtoMessage() {}

func (x *MyRegionsListResp) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyRegionsListResp.ProtoReflect.Descriptor instead.
func (*MyRegionsListResp) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{26}
}

func (x *MyRegionsListResp) GetDefault() *MyRegionsListEntry {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *MyRegionsListResp) GetItems() []*MyRegionsListEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

type MyAzsListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// region under consideration
	Region        string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyAzsListReq) Reset() {
	*x = MyAzsListReq{}
	mi := &file_myaccount_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyAzsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyAzsListReq) ProtoMessage() {}

func (x *MyAzsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyAzsListReq.ProtoReflect.Descriptor instead.
func (*MyAzsListReq) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{27}
}

func (x *MyAzsListReq) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type MyAzsListEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// identifier of the availability zone
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name of the availability zone
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyAzsListEntry) Reset() {
	*x = MyAzsListEntry{}
	mi := &file_myaccount_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyAzsListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyAzsListEntry) ProtoMessage() {}

func (x *MyAzsListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyAzsListEntry.ProtoReflect.Descriptor instead.
func (*MyAzsListEntry) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{28}
}

func (x *MyAzsListEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MyAzsListEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MyAzsListResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// list of available azs for the tenant
	// under a region
	Items         []*MyAzsListEntry `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyAzsListResp) Reset() {
	*x = MyAzsListResp{}
	mi := &file_myaccount_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyAzsListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyAzsListResp) ProtoMessage() {}

func (x *MyAzsListResp) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyAzsListResp.ProtoReflect.Descriptor instead.
func (*MyAzsListResp) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{29}
}

func (x *MyAzsListResp) GetItems() []*MyAzsListEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

// location information derived from IP address
type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// city name
	City string `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	// country name
	Country       string `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_myaccount_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_myaccount_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_myaccount_proto_rawDescGZIP(), []int{30}
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

var File_myaccount_proto protoreflect.FileDescriptor

const file_myaccount_proto_rawDesc = "" +
	"\n" +
	"\x0fmyaccount.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x0e\n" +
	"\fMyInfoGetReq\"{\n" +
	"\rMyInfoGetResp\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1c\n" +
	"\tfirstName\x18\x02 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"\xa5\x01\n" +
	"\rMySessionInfo\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\astarted\x18\x02 \x01(\x03R\astarted\x12\x1e\n" +
	"\n" +
	"lastAccess\x18\x03 \x01(\x03R\n" +
	"lastAccess\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12$\n" +
	"\x03loc\x18\x05 \x01(\v2\r.api.LocationH\x00R\x03loc\x88\x01\x01B\x06\n" +
	"\x04_loc\"=\n" +
	"\x11MySessionsGetResp\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.api.MySessionInfoR\x05items\"3\n" +
	"\x13MySessionsLogoutReq\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14MySessionsLogoutResp\"A\n" +
	"\x0fApiKeyCreateReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bvalidity\x18\x02 \x01(\x03R\bvalidity\"<\n" +
	"\tApiKeyDef\"/\n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06Active\x10\x00\x12\v\n" +
	"\aExpired\x10\x01\x12\f\n" +
	"\bDisabled\x10\x02\"\xcf\x01\n" +
	"\x10ApiKeyCreateResp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.api.ApiKeyDef.StatusR\x06status\x12\x1a\n" +
	"\blastUsed\x18\x04 \x01(\x03R\blastUsed\x12\x18\n" +
	"\acreated\x18\x05 \x01(\x03R\acreated\x12\x1a\n" +
	"\bexpireAt\x18\x06 \x01(\x03R\bexpireAt\x12\x16\n" +
	"\x06secret\x18\a \x01(\tR\x06secret\"\"\n" +
	"\x10ApiKeyDisableReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11ApiKeyDisableResp\"!\n" +
	"\x0fApiKeyEnableReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x12\n" +
	"\x10ApiKeyEnableResp\"!\n" +
	"\x0fApiKeyDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x12\n" +
	"\x10ApiKeyDeleteResp\"\x10\n" +
	"\x0eApiKeysListReq\"\xb6\x01\n" +
	"\x0fApiKeyListEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.api.ApiKeyDef.StatusR\x06status\x12\x1a\n" +
	"\blastUsed\x18\x04 \x01(\x03R\blastUsed\x12\x18\n" +
	"\acreated\x18\x05 \x01(\x03R\acreated\x12\x1a\n" +
	"\bexpireAt\x18\x06 \x01(\x03R\bexpireAt\"=\n" +
	"\x0fApiKeysListResp\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.api.ApiKeyListEntryR\x05items\"\x12\n" +
	"\x10MySessionsGetReq\"\x13\n" +
	"\x11MyOrgUnitsListReq\"4\n" +
	"\x0eMyOrgUnitEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"n\n" +
	"\x12MyOrgUnitsListResp\x12-\n" +
	"\adefault\x18\x01 \x01(\v2\x13.api.MyOrgUnitEntryR\adefault\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.api.MyOrgUnitEntryR\x05items\"#\n" +
	"\x11DefaultOrgUnitReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DefaultOrgUnitResp\"\x12\n" +
	"\x10MyRegionsListReq\"8\n" +
	"\x12MyRegionsListEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"u\n" +
	"\x11MyRegionsListResp\x121\n" +
	"\adefault\x18\x01 \x01(\v2\x17.api.MyRegionsListEntryR\adefault\x12-\n" +
	"\x05items\x18\x02 \x03(\v2\x17.api.MyRegionsListEntryR\x05items\"&\n" +
	"\fMyAzsListReq\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\"4\n" +
	"\x0eMyAzsListEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\":\n" +
	"\rMyAzsListResp\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.api.MyAzsListEntryR\x05items\"8\n" +
	"\bLocation\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry2\xe1\t\n" +
	"\tMyAccount\x12R\n" +
	"\tGetMyInfo\x12\x11.api.MyInfoGetReq\x1a\x12.api.MyInfoGetResp\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/myaccount/v1/info\x12b\n" +
	"\rGetMySessions\x12\x15.api.MySessionsGetReq\x1a\x16.api.MySessionsGetResp\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/myaccount/v1/sessions\x12u\n" +
	"\x10LogoutMySessions\x12\x18.api.MySessionsLogoutReq\x1a\x19.api.MySessionsLogoutResp\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/myaccount/v1/logout-sessions\x12a\n" +
	"\fCreateApiKey\x12\x14.api.ApiKeyCreateReq\x1a\x15.api.ApiKeyCreateResp\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/myaccount/v1/api-key\x12n\n" +
	"\rDisableApiKey\x12\x15.api.ApiKeyDisableReq\x1a\x16.api.ApiKeyDisableResp\".\x82\xd3\xe4\x93\x02(\"&/api/myaccount/v1/api-key/{id}/disable\x12j\n" +
	"\fEnableApiKey\x12\x14.api.ApiKeyEnableReq\x1a\x15.api.ApiKeyEnableResp\"-\x82\xd3\xe4\x93\x02'\"%/api/myaccount/v1/api-key/{id}/enable\x12c\n" +
	"\fDeleteApiKey\x12\x14.api.ApiKeyDeleteReq\x1a\x15.api.ApiKeyDeleteResp\"&\x82\xd3\xe4\x93\x02 *\x1e/api/myaccount/v1/api-key/{id}\x12\\\n" +
	"\vListApiKeys\x12\x13.api.ApiKeysListReq\x1a\x14.api.ApiKeysListResp\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/myaccount/v1/api-keys\x12f\n" +
	"\x0eListMyOrgUnits\x12\x16.api.MyOrgUnitsListReq\x1a\x17.api.MyOrgUnitsListResp\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/myaccount/v1/org-units\x12u\n" +
	"\x11SetDefaultOrgUnit\x12\x16.api.DefaultOrgUnitReq\x1a\x17.api.DefaultOrgUnitResp\"/\x82\xd3\xe4\x93\x02)\"'/api/myaccount/v1/org-unit/{id}/default\x12a\n" +
	"\rListMyRegions\x12\x15.api.MyRegionsListReq\x1a\x16.api.MyRegionsListResp\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/myaccount/v1/regions\x12a\n" +
	"\tListMyAzs\x12\x11.api.MyAzsListReq\x1a\x12.api.MyAzsListResp\"-\x82\xd3\xe4\x93\x02'\x12%/api/myaccount/v1/region/{region}/azsB\x98\x01\x92Aj\x12%\n" +
	"\x1eAuth Gateway API Specification2\x031.0rA\n" +
	"?Auth Gateway API Specification - sample descriptive informationZ)github.com/go-core-stack/auth-gateway/apib\x06proto3"

var (
	file_myaccount_proto_rawDescOnce sync.Once
	file_myaccount_proto_rawDescData []byte
)

func file_myaccount_proto_rawDescGZIP() []byte {
	file_myaccount_proto_rawDescOnce.Do(func() {
		file_myaccount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_myaccount_proto_rawDesc), len(file_myaccount_proto_rawDesc)))
	})
	return file_myaccount_proto_rawDescData
}

var file_myaccount_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_myaccount_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_myaccount_proto_goTypes = []any{
	(ApiKeyDef_Status)(0),        // 0: api.ApiKeyDef.Status
	(*MyInfoGetReq)(nil),         // 1: api.MyInfoGetReq
	(*MyInfoGetResp)(nil),        // 2: api.MyInfoGetResp
	(*MySessionInfo)(nil),        // 3: api.MySessionInfo
	(*MySessionsGetResp)(nil),    // 4: api.MySessionsGetResp
	(*MySessionsLogoutReq)(nil),  // 5: api.MySessionsLogoutReq
	(*MySessionsLogoutResp)(nil), // 6: api.MySessionsLogoutResp
	(*ApiKeyCreateReq)(nil),      // 7: api.ApiKeyCreateReq
	(*ApiKeyDef)(nil),            // 8: api.ApiKeyDef
	(*ApiKeyCreateResp)(nil),     // 9: api.ApiKeyCreateResp
	(*ApiKeyDisableReq)(nil),     // 10: api.ApiKeyDisableReq
	(*ApiKeyDisableResp)(nil),    // 11: api.ApiKeyDisableResp
	(*ApiKeyEnableReq)(nil),      // 12: api.ApiKeyEnableReq
	(*ApiKeyEnableResp)(nil),     // 13: api.ApiKeyEnableResp
	(*ApiKeyDeleteReq)(nil),      // 14: api.ApiKeyDeleteReq
	(*ApiKeyDeleteResp)(nil),     // 15: api.ApiKeyDeleteResp
	(*ApiKeysListReq)(nil),       // 16: api.ApiKeysListReq
	(*ApiKeyListEntry)(nil),      // 17: api.ApiKeyListEntry
	(*ApiKeysListResp)(nil),      // 18: api.ApiKeysListResp
	(*MySessionsGetReq)(nil),     // 19: api.MySessionsGetReq
	(*MyOrgUnitsListReq)(nil),    // 20: api.MyOrgUnitsListReq
	(*MyOrgUnitEntry)(nil),       // 21: api.MyOrgUnitEntry
	(*MyOrgUnitsListResp)(nil),   // 22: api.MyOrgUnitsListResp
	(*DefaultOrgUnitReq)(nil),    // 23: api.DefaultOrgUnitReq
	(*DefaultOrgUnitResp)(nil),   // 24: api.DefaultOrgUnitResp
	(*MyRegionsListReq)(nil),     // 25: api.MyRegionsListReq
	(*MyRegionsListEntry)(nil),   // 26: api.MyRegionsListEntry
	(*MyRegionsListResp)(nil),    // 27: api.MyRegionsListResp
	(*MyAzsListReq)(nil),         // 28: api.MyAzsListReq
	(*MyAzsListEntry)(nil),       // 29: api.MyAzsListEntry
	(*MyAzsListResp)(nil),        // 30: api.MyAzsListResp
	(*Location)(nil),             // 31: api.Location
}
var file_myaccount_proto_depIdxs = []int32{
	31, // 0: api.MySessionInfo.loc:type_name -> api.Location
	3,  // 1: api.MySessionsGetResp.items:type_name -> api.MySessionInfo
	0,  // 2: api.ApiKeyCreateResp.status:type_name -> api.ApiKeyDef.Status
	0,  // 3: api.ApiKeyListEntry.status:type_name -> api.ApiKeyDef.Status
	17, // 4: api.ApiKeysListResp.items:type_name -> api.ApiKeyListEntry
	21, // 5: api.MyOrgUnitsListResp.default:type_name -> api.MyOrgUnitEntry
	21, // 6: api.MyOrgUnitsListResp.items:type_name -> api.MyOrgUnitEntry
	26, // 7: api.MyRegionsListResp.default:type_name -> api.MyRegionsListEntry
	26, // 8: api.MyRegionsListResp.items:type_name -> api.MyRegionsListEntry
	29, // 9: api.MyAzsListResp.items:type_name -> api.MyAzsListEntry
	1,  // 10: api.MyAccount.GetMyInfo:input_type -> api.MyInfoGetReq
	19, // 11: api.MyAccount.GetMySessions:input_type -> api.MySessionsGetReq
	5,  // 12: api.MyAccount.LogoutMySessions:input_type -> api.MySessionsLogoutReq
	7,  // 13: api.MyAccount.CreateApiKey:input_type -> api.ApiKeyCreateReq
	10, // 14: api.MyAccount.DisableApiKey:input_type -> api.ApiKeyDisableReq
	12, // 15: api.MyAccount.EnableApiKey:input_type -> api.ApiKeyEnableReq
	14, // 16: api.MyAccount.DeleteApiKey:input_type -> api.ApiKeyDeleteReq
	16, // 17: api.MyAccount.ListApiKeys:input_type -> api.ApiKeysListReq
	20, // 18: api.MyAccount.ListMyOrgUnits:input_type -> api.MyOrgUnitsListReq
	23, // 19: api.MyAccount.SetDefaultOrgUnit:input_type -> api.DefaultOrgUnitReq
	25, // 20: api.MyAccount.ListMyRegions:input_type -> api.MyRegionsListReq
	28, // 21: api.MyAccount.ListMyAzs:input_type -> api.MyAzsListReq
	2,  // 22: api.MyAccount.GetMyInfo:output_type -> api.MyInfoGetResp
	4,  // 23: api.MyAccount.GetMySessions:output_type -> api.MySessionsGetResp
	6,  // 24: api.MyAccount.LogoutMySessions:output_type -> api.MySessionsLogoutResp
	9,  // 25: api.MyAccount.CreateApiKey:output_type -> api.ApiKeyCreateResp
	11, // 26: api.MyAccount.DisableApiKey:output_type -> api.ApiKeyDisableResp
	13, // 27: api.MyAccount.EnableApiKey:output_type -> api.ApiKeyEnableResp
	15, // 28: api.MyAccount.DeleteApiKey:output_type -> api.ApiKeyDeleteResp
	18, // 29: api.MyAccount.ListApiKeys:output_type -> api.ApiKeysListResp
	22, // 30: api.MyAccount.ListMyOrgUnits:output_type -> api.MyOrgUnitsListResp
	24, // 31: api.MyAccount.SetDefaultOrgUnit:output_type -> api.DefaultOrgUnitResp
	27, // 32: api.MyAccount.ListMyRegions:output_type -> api.MyRegionsListResp
	30, // 33: api.MyAccount.ListMyAzs:output_type -> api.MyAzsListResp
	22, // [22:34] is the sub-list for method output_type
	10, // [10:22] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_myaccount_proto_init() }
func file_myaccount_proto_init() {
	if File_myaccount_proto != nil {
		return
	}
	file_myaccount_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_myaccount_proto_rawDesc), len(file_myaccount_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myaccount_proto_goTypes,
		DependencyIndexes: file_myaccount_proto_depIdxs,
		EnumInfos:         file_myaccount_proto_enumTypes,
		MessageInfos:      file_myaccount_proto_msgTypes,
	}.Build()
	File_myaccount_proto = out.File
	file_myaccount_proto_goTypes = nil
	file_myaccount_proto_depIdxs = nil
}
