// Copyright © 2025 Prabhjot Singh Sethi, All Rights reserved
// Author: Prabhjot Singh Sethi <prabhjot.sethi@gmail.com>

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: mytenant.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MyTenant_GetMyPasswordPolicy_FullMethodName            = "/api.MyTenant/GetMyPasswordPolicy"
	MyTenant_UpdateMyPasswordPolicy_FullMethodName         = "/api.MyTenant/UpdateMyPasswordPolicy"
	MyTenant_GetIdentityProviderTypes_FullMethodName       = "/api.MyTenant/GetIdentityProviderTypes"
	MyTenant_CreateIdentityProviderInstance_FullMethodName = "/api.MyTenant/CreateIdentityProviderInstance"
	MyTenant_ListIdentityProviderInstances_FullMethodName  = "/api.MyTenant/ListIdentityProviderInstances"
	MyTenant_GetIdentityProviderInstance_FullMethodName    = "/api.MyTenant/GetIdentityProviderInstance"
	MyTenant_UpdateIdentityProviderInstance_FullMethodName = "/api.MyTenant/UpdateIdentityProviderInstance"
	MyTenant_DeleteIdentityProviderInstance_FullMethodName = "/api.MyTenant/DeleteIdentityProviderInstance"
)

// MyTenantClient is the client API for MyTenant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// service provided to manage tenant configuration
type MyTenantClient interface {
	// Get Password policy configuration
	GetMyPasswordPolicy(ctx context.Context, in *MyPasswordPolicyGetReq, opts ...grpc.CallOption) (*MyPasswordPolicyGetResp, error)
	// Update Password policy configuration
	UpdateMyPasswordPolicy(ctx context.Context, in *MyPasswordPolicyUpdateReq, opts ...grpc.CallOption) (*MyPasswordPolicyUpdateResp, error)
	// List supported identity provider types (like Keycloak providers endpoint)
	GetIdentityProviderTypes(ctx context.Context, in *IdpProvidersReq, opts ...grpc.CallOption) (*IdpProvidersResp, error)
	// Create identity provider instance (like Keycloak instances endpoint)
	CreateIdentityProviderInstance(ctx context.Context, in *IdpInstanceCreateReq, opts ...grpc.CallOption) (*IdpInstanceCreateResp, error)
	// List all configured identity provider instances for the tenant
	ListIdentityProviderInstances(ctx context.Context, in *IdpInstanceListReq, opts ...grpc.CallOption) (*IdpInstanceListResp, error)
	// Get identity provider instance configuration (like Keycloak instances endpoint)
	GetIdentityProviderInstance(ctx context.Context, in *IdpInstanceGetReq, opts ...grpc.CallOption) (*IdpInstanceGetResp, error)
	// Update identity provider instance configuration (like Keycloak instances endpoint)
	UpdateIdentityProviderInstance(ctx context.Context, in *IdpInstanceUpdateReq, opts ...grpc.CallOption) (*IdpInstanceUpdateResp, error)
	// Delete identity provider instance (like Keycloak instances endpoint)
	DeleteIdentityProviderInstance(ctx context.Context, in *IdpInstanceDeleteReq, opts ...grpc.CallOption) (*IdpInstanceDeleteResp, error)
}

type myTenantClient struct {
	cc grpc.ClientConnInterface
}

func NewMyTenantClient(cc grpc.ClientConnInterface) MyTenantClient {
	return &myTenantClient{cc}
}

func (c *myTenantClient) GetMyPasswordPolicy(ctx context.Context, in *MyPasswordPolicyGetReq, opts ...grpc.CallOption) (*MyPasswordPolicyGetResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MyPasswordPolicyGetResp)
	err := c.cc.Invoke(ctx, MyTenant_GetMyPasswordPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myTenantClient) UpdateMyPasswordPolicy(ctx context.Context, in *MyPasswordPolicyUpdateReq, opts ...grpc.CallOption) (*MyPasswordPolicyUpdateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MyPasswordPolicyUpdateResp)
	err := c.cc.Invoke(ctx, MyTenant_UpdateMyPasswordPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myTenantClient) GetIdentityProviderTypes(ctx context.Context, in *IdpProvidersReq, opts ...grpc.CallOption) (*IdpProvidersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdpProvidersResp)
	err := c.cc.Invoke(ctx, MyTenant_GetIdentityProviderTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myTenantClient) CreateIdentityProviderInstance(ctx context.Context, in *IdpInstanceCreateReq, opts ...grpc.CallOption) (*IdpInstanceCreateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdpInstanceCreateResp)
	err := c.cc.Invoke(ctx, MyTenant_CreateIdentityProviderInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myTenantClient) ListIdentityProviderInstances(ctx context.Context, in *IdpInstanceListReq, opts ...grpc.CallOption) (*IdpInstanceListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdpInstanceListResp)
	err := c.cc.Invoke(ctx, MyTenant_ListIdentityProviderInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myTenantClient) GetIdentityProviderInstance(ctx context.Context, in *IdpInstanceGetReq, opts ...grpc.CallOption) (*IdpInstanceGetResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdpInstanceGetResp)
	err := c.cc.Invoke(ctx, MyTenant_GetIdentityProviderInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myTenantClient) UpdateIdentityProviderInstance(ctx context.Context, in *IdpInstanceUpdateReq, opts ...grpc.CallOption) (*IdpInstanceUpdateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdpInstanceUpdateResp)
	err := c.cc.Invoke(ctx, MyTenant_UpdateIdentityProviderInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myTenantClient) DeleteIdentityProviderInstance(ctx context.Context, in *IdpInstanceDeleteReq, opts ...grpc.CallOption) (*IdpInstanceDeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdpInstanceDeleteResp)
	err := c.cc.Invoke(ctx, MyTenant_DeleteIdentityProviderInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyTenantServer is the server API for MyTenant service.
// All implementations must embed UnimplementedMyTenantServer
// for forward compatibility.
//
// service provided to manage tenant configuration
type MyTenantServer interface {
	// Get Password policy configuration
	GetMyPasswordPolicy(context.Context, *MyPasswordPolicyGetReq) (*MyPasswordPolicyGetResp, error)
	// Update Password policy configuration
	UpdateMyPasswordPolicy(context.Context, *MyPasswordPolicyUpdateReq) (*MyPasswordPolicyUpdateResp, error)
	// List supported identity provider types (like Keycloak providers endpoint)
	GetIdentityProviderTypes(context.Context, *IdpProvidersReq) (*IdpProvidersResp, error)
	// Create identity provider instance (like Keycloak instances endpoint)
	CreateIdentityProviderInstance(context.Context, *IdpInstanceCreateReq) (*IdpInstanceCreateResp, error)
	// List all configured identity provider instances for the tenant
	ListIdentityProviderInstances(context.Context, *IdpInstanceListReq) (*IdpInstanceListResp, error)
	// Get identity provider instance configuration (like Keycloak instances endpoint)
	GetIdentityProviderInstance(context.Context, *IdpInstanceGetReq) (*IdpInstanceGetResp, error)
	// Update identity provider instance configuration (like Keycloak instances endpoint)
	UpdateIdentityProviderInstance(context.Context, *IdpInstanceUpdateReq) (*IdpInstanceUpdateResp, error)
	// Delete identity provider instance (like Keycloak instances endpoint)
	DeleteIdentityProviderInstance(context.Context, *IdpInstanceDeleteReq) (*IdpInstanceDeleteResp, error)
	mustEmbedUnimplementedMyTenantServer()
}

// UnimplementedMyTenantServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMyTenantServer struct{}

func (UnimplementedMyTenantServer) GetMyPasswordPolicy(context.Context, *MyPasswordPolicyGetReq) (*MyPasswordPolicyGetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyPasswordPolicy not implemented")
}
func (UnimplementedMyTenantServer) UpdateMyPasswordPolicy(context.Context, *MyPasswordPolicyUpdateReq) (*MyPasswordPolicyUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMyPasswordPolicy not implemented")
}
func (UnimplementedMyTenantServer) GetIdentityProviderTypes(context.Context, *IdpProvidersReq) (*IdpProvidersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentityProviderTypes not implemented")
}
func (UnimplementedMyTenantServer) CreateIdentityProviderInstance(context.Context, *IdpInstanceCreateReq) (*IdpInstanceCreateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIdentityProviderInstance not implemented")
}
func (UnimplementedMyTenantServer) ListIdentityProviderInstances(context.Context, *IdpInstanceListReq) (*IdpInstanceListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIdentityProviderInstances not implemented")
}
func (UnimplementedMyTenantServer) GetIdentityProviderInstance(context.Context, *IdpInstanceGetReq) (*IdpInstanceGetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentityProviderInstance not implemented")
}
func (UnimplementedMyTenantServer) UpdateIdentityProviderInstance(context.Context, *IdpInstanceUpdateReq) (*IdpInstanceUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateIdentityProviderInstance not implemented")
}
func (UnimplementedMyTenantServer) DeleteIdentityProviderInstance(context.Context, *IdpInstanceDeleteReq) (*IdpInstanceDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIdentityProviderInstance not implemented")
}
func (UnimplementedMyTenantServer) mustEmbedUnimplementedMyTenantServer() {}
func (UnimplementedMyTenantServer) testEmbeddedByValue()                  {}

// UnsafeMyTenantServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyTenantServer will
// result in compilation errors.
type UnsafeMyTenantServer interface {
	mustEmbedUnimplementedMyTenantServer()
}

func RegisterMyTenantServer(s grpc.ServiceRegistrar, srv MyTenantServer) {
	// If the following call pancis, it indicates UnimplementedMyTenantServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MyTenant_ServiceDesc, srv)
}

func _MyTenant_GetMyPasswordPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyPasswordPolicyGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyTenantServer).GetMyPasswordPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyTenant_GetMyPasswordPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyTenantServer).GetMyPasswordPolicy(ctx, req.(*MyPasswordPolicyGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyTenant_UpdateMyPasswordPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyPasswordPolicyUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyTenantServer).UpdateMyPasswordPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyTenant_UpdateMyPasswordPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyTenantServer).UpdateMyPasswordPolicy(ctx, req.(*MyPasswordPolicyUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyTenant_GetIdentityProviderTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdpProvidersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyTenantServer).GetIdentityProviderTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyTenant_GetIdentityProviderTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyTenantServer).GetIdentityProviderTypes(ctx, req.(*IdpProvidersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyTenant_CreateIdentityProviderInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdpInstanceCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyTenantServer).CreateIdentityProviderInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyTenant_CreateIdentityProviderInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyTenantServer).CreateIdentityProviderInstance(ctx, req.(*IdpInstanceCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyTenant_ListIdentityProviderInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdpInstanceListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyTenantServer).ListIdentityProviderInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyTenant_ListIdentityProviderInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyTenantServer).ListIdentityProviderInstances(ctx, req.(*IdpInstanceListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyTenant_GetIdentityProviderInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdpInstanceGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyTenantServer).GetIdentityProviderInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyTenant_GetIdentityProviderInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyTenantServer).GetIdentityProviderInstance(ctx, req.(*IdpInstanceGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyTenant_UpdateIdentityProviderInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdpInstanceUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyTenantServer).UpdateIdentityProviderInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyTenant_UpdateIdentityProviderInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyTenantServer).UpdateIdentityProviderInstance(ctx, req.(*IdpInstanceUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyTenant_DeleteIdentityProviderInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdpInstanceDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyTenantServer).DeleteIdentityProviderInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyTenant_DeleteIdentityProviderInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyTenantServer).DeleteIdentityProviderInstance(ctx, req.(*IdpInstanceDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MyTenant_ServiceDesc is the grpc.ServiceDesc for MyTenant service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyTenant_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.MyTenant",
	HandlerType: (*MyTenantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyPasswordPolicy",
			Handler:    _MyTenant_GetMyPasswordPolicy_Handler,
		},
		{
			MethodName: "UpdateMyPasswordPolicy",
			Handler:    _MyTenant_UpdateMyPasswordPolicy_Handler,
		},
		{
			MethodName: "GetIdentityProviderTypes",
			Handler:    _MyTenant_GetIdentityProviderTypes_Handler,
		},
		{
			MethodName: "CreateIdentityProviderInstance",
			Handler:    _MyTenant_CreateIdentityProviderInstance_Handler,
		},
		{
			MethodName: "ListIdentityProviderInstances",
			Handler:    _MyTenant_ListIdentityProviderInstances_Handler,
		},
		{
			MethodName: "GetIdentityProviderInstance",
			Handler:    _MyTenant_GetIdentityProviderInstance_Handler,
		},
		{
			MethodName: "UpdateIdentityProviderInstance",
			Handler:    _MyTenant_UpdateIdentityProviderInstance_Handler,
		},
		{
			MethodName: "DeleteIdentityProviderInstance",
			Handler:    _MyTenant_DeleteIdentityProviderInstance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mytenant.proto",
}
