// Code generated by protoc-gen-routes. DO NOT EDIT.
// source: mytenant.proto

package api

import "github.com/go-core-stack/auth/model"

var RoutesMyTenant = []*model.Route{}

func init() {
	var route *model.Route

	// Adding Route information for GetMyPasswordPolicy RPC
	route = model.NewRoute("/api/mytenant/v1/password-policy", "GET")
	route.Resource = "password-policy"
	route.Verb = "get"
	RoutesMyTenant = append(RoutesMyTenant, route)

	// Adding Route information for UpdateMyPasswordPolicy RPC
	route = model.NewRoute("/api/mytenant/v1/password-policy", "PUT")
	route.Resource = "password-policy"
	route.Verb = "update"
	RoutesMyTenant = append(RoutesMyTenant, route)

	// Adding Route information for GetKeycloakSessionLimitsInstructions RPC
	route = model.NewRoute("/api/mytenant/v1/keycloak-session-limits", "GET")
	route.Resource = "session-limits"
	route.Verb = "get"
	RoutesMyTenant = append(RoutesMyTenant, route)

	// Adding Route information for ConfigureKeycloakSessionLimits RPC
	route = model.NewRoute("/api/mytenant/v1/keycloak-session-limits", "PUT")
	route.Resource = "session-limits"
	route.Verb = "update"
	RoutesMyTenant = append(RoutesMyTenant, route)
}
