// Copyright © 2025 Prabhjot Singh Sethi, All Rights reserved
// Author: Prabhjot Singh Sethi <prabhjot.sethi@gmail.com>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: org-unit.proto

package api

import (
	_ "github.com/go-core-stack/grpc-core/coreapis/api"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// list org units for my tenant
// typically available only for tenant admin
type OrgUnitsListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// offset from where to start the list of org units
	Offset int32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// limit the response to specified count
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgUnitsListReq) Reset() {
	*x = OrgUnitsListReq{}
	mi := &file_org_unit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgUnitsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgUnitsListReq) ProtoMessage() {}

func (x *OrgUnitsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_org_unit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgUnitsListReq.ProtoReflect.Descriptor instead.
func (*OrgUnitsListReq) Descriptor() ([]byte, []int) {
	return file_org_unit_proto_rawDescGZIP(), []int{0}
}

func (x *OrgUnitsListReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *OrgUnitsListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type OrgUnitsListEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// org unit id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// org unit display name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// org unit description
	Desc string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	// created by
	CreatedBy string `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	// create time
	Created       int64 `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgUnitsListEntry) Reset() {
	*x = OrgUnitsListEntry{}
	mi := &file_org_unit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgUnitsListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgUnitsListEntry) ProtoMessage() {}

func (x *OrgUnitsListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_org_unit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgUnitsListEntry.ProtoReflect.Descriptor instead.
func (*OrgUnitsListEntry) Descriptor() ([]byte, []int) {
	return file_org_unit_proto_rawDescGZIP(), []int{1}
}

func (x *OrgUnitsListEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrgUnitsListEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrgUnitsListEntry) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *OrgUnitsListEntry) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *OrgUnitsListEntry) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

// list org units response
type OrgUnitsListResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// count of Org units available
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// list of org unit info in response
	Items         []*OrgUnitsListEntry `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgUnitsListResp) Reset() {
	*x = OrgUnitsListResp{}
	mi := &file_org_unit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgUnitsListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgUnitsListResp) ProtoMessage() {}

func (x *OrgUnitsListResp) ProtoReflect() protoreflect.Message {
	mi := &file_org_unit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgUnitsListResp.ProtoReflect.Descriptor instead.
func (*OrgUnitsListResp) Descriptor() ([]byte, []int) {
	return file_org_unit_proto_rawDescGZIP(), []int{2}
}

func (x *OrgUnitsListResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *OrgUnitsListResp) GetItems() []*OrgUnitsListEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

// request for creation of new org unit
type OrgUnitCreateReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// display name for the org unit
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// org unit description
	Desc          string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgUnitCreateReq) Reset() {
	*x = OrgUnitCreateReq{}
	mi := &file_org_unit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgUnitCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgUnitCreateReq) ProtoMessage() {}

func (x *OrgUnitCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_org_unit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgUnitCreateReq.ProtoReflect.Descriptor instead.
func (*OrgUnitCreateReq) Descriptor() ([]byte, []int) {
	return file_org_unit_proto_rawDescGZIP(), []int{3}
}

func (x *OrgUnitCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrgUnitCreateReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

// response for creation of new org unit
type OrgUnitCreateResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the org unit created
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgUnitCreateResp) Reset() {
	*x = OrgUnitCreateResp{}
	mi := &file_org_unit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgUnitCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgUnitCreateResp) ProtoMessage() {}

func (x *OrgUnitCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_org_unit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgUnitCreateResp.ProtoReflect.Descriptor instead.
func (*OrgUnitCreateResp) Descriptor() ([]byte, []int) {
	return file_org_unit_proto_rawDescGZIP(), []int{4}
}

func (x *OrgUnitCreateResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// request for update of an existing org unit
type OrgUnitUpdateReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the org unit
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// display name for the org unit
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// org unit description
	Desc          string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgUnitUpdateReq) Reset() {
	*x = OrgUnitUpdateReq{}
	mi := &file_org_unit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgUnitUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgUnitUpdateReq) ProtoMessage() {}

func (x *OrgUnitUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_org_unit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgUnitUpdateReq.ProtoReflect.Descriptor instead.
func (*OrgUnitUpdateReq) Descriptor() ([]byte, []int) {
	return file_org_unit_proto_rawDescGZIP(), []int{5}
}

func (x *OrgUnitUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrgUnitUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrgUnitUpdateReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type OrgUnitUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgUnitUpdateResp) Reset() {
	*x = OrgUnitUpdateResp{}
	mi := &file_org_unit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgUnitUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgUnitUpdateResp) ProtoMessage() {}

func (x *OrgUnitUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_org_unit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgUnitUpdateResp.ProtoReflect.Descriptor instead.
func (*OrgUnitUpdateResp) Descriptor() ([]byte, []int) {
	return file_org_unit_proto_rawDescGZIP(), []int{6}
}

// org unit get request
type OrgUnitGetReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the org unit
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgUnitGetReq) Reset() {
	*x = OrgUnitGetReq{}
	mi := &file_org_unit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgUnitGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgUnitGetReq) ProtoMessage() {}

func (x *OrgUnitGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_org_unit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgUnitGetReq.ProtoReflect.Descriptor instead.
func (*OrgUnitGetReq) Descriptor() ([]byte, []int) {
	return file_org_unit_proto_rawDescGZIP(), []int{7}
}

func (x *OrgUnitGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OrgUnitGetResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// org unit id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// org unit display name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// org unit description
	Desc string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	// created by
	CreatedBy string `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	// create time
	Created       int64 `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgUnitGetResp) Reset() {
	*x = OrgUnitGetResp{}
	mi := &file_org_unit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgUnitGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgUnitGetResp) ProtoMessage() {}

func (x *OrgUnitGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_org_unit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgUnitGetResp.ProtoReflect.Descriptor instead.
func (*OrgUnitGetResp) Descriptor() ([]byte, []int) {
	return file_org_unit_proto_rawDescGZIP(), []int{8}
}

func (x *OrgUnitGetResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrgUnitGetResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrgUnitGetResp) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *OrgUnitGetResp) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *OrgUnitGetResp) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

// delete org unit req
type OrgUnitDeleteReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// org unit id
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgUnitDeleteReq) Reset() {
	*x = OrgUnitDeleteReq{}
	mi := &file_org_unit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgUnitDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgUnitDeleteReq) ProtoMessage() {}

func (x *OrgUnitDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_org_unit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgUnitDeleteReq.ProtoReflect.Descriptor instead.
func (*OrgUnitDeleteReq) Descriptor() ([]byte, []int) {
	return file_org_unit_proto_rawDescGZIP(), []int{9}
}

func (x *OrgUnitDeleteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OrgUnitDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgUnitDeleteResp) Reset() {
	*x = OrgUnitDeleteResp{}
	mi := &file_org_unit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgUnitDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgUnitDeleteResp) ProtoMessage() {}

func (x *OrgUnitDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_org_unit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgUnitDeleteResp.ProtoReflect.Descriptor instead.
func (*OrgUnitDeleteResp) Descriptor() ([]byte, []int) {
	return file_org_unit_proto_rawDescGZIP(), []int{10}
}

var File_org_unit_proto protoreflect.FileDescriptor

const file_org_unit_proto_rawDesc = "" +
	"\n" +
	"\x0eorg-unit.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x17coreapis/api/role.proto\"?\n" +
	"\x0fOrgUnitsListReq\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x83\x01\n" +
	"\x11OrgUnitsListEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x1c\n" +
	"\tcreatedBy\x18\x04 \x01(\tR\tcreatedBy\x12\x18\n" +
	"\acreated\x18\x05 \x01(\x03R\acreated\"V\n" +
	"\x10OrgUnitsListResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.api.OrgUnitsListEntryR\x05items\":\n" +
	"\x10OrgUnitCreateReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\"#\n" +
	"\x11OrgUnitCreateResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x10OrgUnitUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\"\x13\n" +
	"\x11OrgUnitUpdateResp\"\x1f\n" +
	"\rOrgUnitGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x80\x01\n" +
	"\x0eOrgUnitGetResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x1c\n" +
	"\tcreatedBy\x18\x04 \x01(\tR\tcreatedBy\x12\x18\n" +
	"\acreated\x18\x05 \x01(\x03R\acreated\"\"\n" +
	"\x10OrgUnitDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11OrgUnitDeleteResp2\xcd\x04\n" +
	"\aOrgUnit\x12m\n" +
	"\fListOrgUnits\x12\x14.api.OrgUnitsListReq\x1a\x15.api.OrgUnitsListResp\"0\x8a\xb5\x18\x10\n" +
	"\borg-unit\x1a\x04list\x82\xd3\xe4\x93\x02\x16\x12\x14/api/mytenant/v1/ous\x12t\n" +
	"\rCreateOrgUnit\x12\x15.api.OrgUnitCreateReq\x1a\x16.api.OrgUnitCreateResp\"4\x8a\xb5\x18\x12\n" +
	"\borg-unit\x1a\x06create\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/mytenant/v1/ou\x12y\n" +
	"\rUpdateOrgUnit\x12\x15.api.OrgUnitUpdateReq\x1a\x16.api.OrgUnitUpdateResp\"9\x8a\xb5\x18\x12\n" +
	"\borg-unit\x1a\x06update\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/api/mytenant/v1/ou/{id}\x12j\n" +
	"\n" +
	"GetOrgUnit\x12\x12.api.OrgUnitGetReq\x1a\x13.api.OrgUnitGetResp\"3\x8a\xb5\x18\x0f\n" +
	"\borg-unit\x1a\x03get\x82\xd3\xe4\x93\x02\x1a\x12\x18/api/mytenant/v1/ou/{id}\x12v\n" +
	"\rDeleteOrgUnit\x12\x15.api.OrgUnitDeleteReq\x1a\x16.api.OrgUnitDeleteResp\"6\x8a\xb5\x18\x12\n" +
	"\borg-unit\x1a\x06delete\x82\xd3\xe4\x93\x02\x1a*\x18/api/mytenant/v1/ou/{id}B+Z)github.com/go-core-stack/auth-gateway/apib\x06proto3"

var (
	file_org_unit_proto_rawDescOnce sync.Once
	file_org_unit_proto_rawDescData []byte
)

func file_org_unit_proto_rawDescGZIP() []byte {
	file_org_unit_proto_rawDescOnce.Do(func() {
		file_org_unit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_unit_proto_rawDesc), len(file_org_unit_proto_rawDesc)))
	})
	return file_org_unit_proto_rawDescData
}

var file_org_unit_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_org_unit_proto_goTypes = []any{
	(*OrgUnitsListReq)(nil),   // 0: api.OrgUnitsListReq
	(*OrgUnitsListEntry)(nil), // 1: api.OrgUnitsListEntry
	(*OrgUnitsListResp)(nil),  // 2: api.OrgUnitsListResp
	(*OrgUnitCreateReq)(nil),  // 3: api.OrgUnitCreateReq
	(*OrgUnitCreateResp)(nil), // 4: api.OrgUnitCreateResp
	(*OrgUnitUpdateReq)(nil),  // 5: api.OrgUnitUpdateReq
	(*OrgUnitUpdateResp)(nil), // 6: api.OrgUnitUpdateResp
	(*OrgUnitGetReq)(nil),     // 7: api.OrgUnitGetReq
	(*OrgUnitGetResp)(nil),    // 8: api.OrgUnitGetResp
	(*OrgUnitDeleteReq)(nil),  // 9: api.OrgUnitDeleteReq
	(*OrgUnitDeleteResp)(nil), // 10: api.OrgUnitDeleteResp
}
var file_org_unit_proto_depIdxs = []int32{
	1,  // 0: api.OrgUnitsListResp.items:type_name -> api.OrgUnitsListEntry
	0,  // 1: api.OrgUnit.ListOrgUnits:input_type -> api.OrgUnitsListReq
	3,  // 2: api.OrgUnit.CreateOrgUnit:input_type -> api.OrgUnitCreateReq
	5,  // 3: api.OrgUnit.UpdateOrgUnit:input_type -> api.OrgUnitUpdateReq
	7,  // 4: api.OrgUnit.GetOrgUnit:input_type -> api.OrgUnitGetReq
	9,  // 5: api.OrgUnit.DeleteOrgUnit:input_type -> api.OrgUnitDeleteReq
	2,  // 6: api.OrgUnit.ListOrgUnits:output_type -> api.OrgUnitsListResp
	4,  // 7: api.OrgUnit.CreateOrgUnit:output_type -> api.OrgUnitCreateResp
	6,  // 8: api.OrgUnit.UpdateOrgUnit:output_type -> api.OrgUnitUpdateResp
	8,  // 9: api.OrgUnit.GetOrgUnit:output_type -> api.OrgUnitGetResp
	10, // 10: api.OrgUnit.DeleteOrgUnit:output_type -> api.OrgUnitDeleteResp
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_org_unit_proto_init() }
func file_org_unit_proto_init() {
	if File_org_unit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_unit_proto_rawDesc), len(file_org_unit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_org_unit_proto_goTypes,
		DependencyIndexes: file_org_unit_proto_depIdxs,
		MessageInfos:      file_org_unit_proto_msgTypes,
	}.Build()
	File_org_unit_proto = out.File
	file_org_unit_proto_goTypes = nil
	file_org_unit_proto_depIdxs = nil
}
