// Code generated by protoc-gen-routes. DO NOT EDIT.
// source: register.proto

package api

import "github.com/go-core-stack/auth/model"

var RoutesRegistration = []*model.Route{}

func init() {
	var route *model.Route

	// Adding Route information for GetRegisterOtp RPC
	route = model.NewRoute("/api/register/v1/otp", "POST")
	RoutesRegistration = append(RoutesRegistration, route)
}
