// Code generated by protoc-gen-routes. DO NOT EDIT.
// source: resdef.proto

package api

import "github.com/go-core-stack/auth/model"

var RoutesResourceDefinition = []*model.Route{}

func init() {
	var route *model.Route

	// Adding Route information for GetResources RPC
	route = model.NewRoute("/api/auth/v1/resources", "GET")
	RoutesResourceDefinition = append(RoutesResourceDefinition, route)
}
