// Copyright © 2025 Prabhjot Singh Sethi, All Rights reserved
// Author: Prabhjot Singh Sethi <prabhjot.sethi@gmail.com>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: resdef.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// resources get request
// eventually this will also need to have scopes field
type ResourceGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceGetReq) Reset() {
	*x = ResourceGetReq{}
	mi := &file_resdef_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceGetReq) ProtoMessage() {}

func (x *ResourceGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_resdef_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceGetReq.ProtoReflect.Descriptor instead.
func (*ResourceGetReq) Descriptor() ([]byte, []int) {
	return file_resdef_proto_rawDescGZIP(), []int{0}
}

// Resource entry
type ResourceEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the resource
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// available verbs
	Verbs         []string `protobuf:"bytes,2,rep,name=verbs,proto3" json:"verbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceEntry) Reset() {
	*x = ResourceEntry{}
	mi := &file_resdef_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEntry) ProtoMessage() {}

func (x *ResourceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_resdef_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceEntry.ProtoReflect.Descriptor instead.
func (*ResourceEntry) Descriptor() ([]byte, []int) {
	return file_resdef_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceEntry) GetVerbs() []string {
	if x != nil {
		return x.Verbs
	}
	return nil
}

// resource get response
type ResourceGetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ResourceEntry       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceGetResp) Reset() {
	*x = ResourceGetResp{}
	mi := &file_resdef_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceGetResp) ProtoMessage() {}

func (x *ResourceGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_resdef_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceGetResp.ProtoReflect.Descriptor instead.
func (*ResourceGetResp) Descriptor() ([]byte, []int) {
	return file_resdef_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceGetResp) GetItems() []*ResourceEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_resdef_proto protoreflect.FileDescriptor

const file_resdef_proto_rawDesc = "" +
	"\n" +
	"\fresdef.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\"\x10\n" +
	"\x0eResourceGetReq\"9\n" +
	"\rResourceEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05verbs\x18\x02 \x03(\tR\x05verbs\";\n" +
	"\x0fResourceGetResp\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.api.ResourceEntryR\x05items2o\n" +
	"\x12ResourceDefinition\x12Y\n" +
	"\fGetResources\x12\x13.api.ResourceGetReq\x1a\x14.api.ResourceGetResp\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/auth/v1/resourcesB,Z*github.com/Prabhjot-Sethi/auth-gateway/apib\x06proto3"

var (
	file_resdef_proto_rawDescOnce sync.Once
	file_resdef_proto_rawDescData []byte
)

func file_resdef_proto_rawDescGZIP() []byte {
	file_resdef_proto_rawDescOnce.Do(func() {
		file_resdef_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resdef_proto_rawDesc), len(file_resdef_proto_rawDesc)))
	})
	return file_resdef_proto_rawDescData
}

var file_resdef_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_resdef_proto_goTypes = []any{
	(*ResourceGetReq)(nil),  // 0: api.ResourceGetReq
	(*ResourceEntry)(nil),   // 1: api.ResourceEntry
	(*ResourceGetResp)(nil), // 2: api.ResourceGetResp
}
var file_resdef_proto_depIdxs = []int32{
	1, // 0: api.ResourceGetResp.items:type_name -> api.ResourceEntry
	0, // 1: api.ResourceDefinition.GetResources:input_type -> api.ResourceGetReq
	2, // 2: api.ResourceDefinition.GetResources:output_type -> api.ResourceGetResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_resdef_proto_init() }
func file_resdef_proto_init() {
	if File_resdef_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resdef_proto_rawDesc), len(file_resdef_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resdef_proto_goTypes,
		DependencyIndexes: file_resdef_proto_depIdxs,
		MessageInfos:      file_resdef_proto_msgTypes,
	}.Build()
	File_resdef_proto = out.File
	file_resdef_proto_goTypes = nil
	file_resdef_proto_depIdxs = nil
}
