// Copyright © 2025 Prabhjot Singh Sethi, All Rights reserved
// Author: Prabhjot Singh Sethi <prabhjot.sethi@gmail.com>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: tenant-user.proto

package api

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request List of users in a tenant
type TenantUsersListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant under which the user list is requested
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// offset from where to start the list of users
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// limit the response to specified count
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// prefix match to consider
	Search        string `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUsersListReq) Reset() {
	*x = TenantUsersListReq{}
	mi := &file_tenant_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUsersListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUsersListReq) ProtoMessage() {}

func (x *TenantUsersListReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUsersListReq.ProtoReflect.Descriptor instead.
func (*TenantUsersListReq) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{0}
}

func (x *TenantUsersListReq) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *TenantUsersListReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TenantUsersListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TenantUsersListReq) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

// user information for the list entry
type TenantUserListEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username or user id
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// user email
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// first name of user
	FirstName string `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	// last name of user
	LastName string `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	// is user enabled
	Enabled bool `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// created since
	CreationTimestamp int64 `protobuf:"varint,6,opt,name=creationTimestamp,proto3" json:"creationTimestamp,omitempty"`
	// last access by the user
	LastAccess    int64 `protobuf:"varint,7,opt,name=lastAccess,proto3" json:"lastAccess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserListEntry) Reset() {
	*x = TenantUserListEntry{}
	mi := &file_tenant_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserListEntry) ProtoMessage() {}

func (x *TenantUserListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserListEntry.ProtoReflect.Descriptor instead.
func (*TenantUserListEntry) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{1}
}

func (x *TenantUserListEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TenantUserListEntry) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TenantUserListEntry) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *TenantUserListEntry) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *TenantUserListEntry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TenantUserListEntry) GetCreationTimestamp() int64 {
	if x != nil {
		return x.CreationTimestamp
	}
	return 0
}

func (x *TenantUserListEntry) GetLastAccess() int64 {
	if x != nil {
		return x.LastAccess
	}
	return 0
}

// Response to the list of users in a tenant
type TenantUsersListResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// number of users in the tenant
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// items - list of users
	Items         []*TenantUserListEntry `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUsersListResp) Reset() {
	*x = TenantUsersListResp{}
	mi := &file_tenant_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUsersListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUsersListResp) ProtoMessage() {}

func (x *TenantUsersListResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUsersListResp.ProtoReflect.Descriptor instead.
func (*TenantUsersListResp) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{2}
}

func (x *TenantUsersListResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TenantUsersListResp) GetItems() []*TenantUserListEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

// user create request message
type TenantUserCreateReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant under which this user will be created
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// user ID
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// email address of the user
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// first name of the user
	Firstname string `protobuf:"bytes,4,opt,name=firstname,proto3" json:"firstname,omitempty"`
	// last name of the user
	Lastname string `protobuf:"bytes,5,opt,name=lastname,proto3" json:"lastname,omitempty"`
	// if the user needs to be created disabled
	Disabled bool `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// temporary first login password to be set for the user
	Password      string `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserCreateReq) Reset() {
	*x = TenantUserCreateReq{}
	mi := &file_tenant_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserCreateReq) ProtoMessage() {}

func (x *TenantUserCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserCreateReq.ProtoReflect.Descriptor instead.
func (*TenantUserCreateReq) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{3}
}

func (x *TenantUserCreateReq) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *TenantUserCreateReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TenantUserCreateReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TenantUserCreateReq) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *TenantUserCreateReq) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *TenantUserCreateReq) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *TenantUserCreateReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// response to user create request
type TenantUserCreateResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username or user id
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// user email
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// first name of user
	FirstName string `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	// last name of user
	LastName string `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	// is user enabled
	Enabled       bool `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserCreateResp) Reset() {
	*x = TenantUserCreateResp{}
	mi := &file_tenant_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserCreateResp) ProtoMessage() {}

func (x *TenantUserCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserCreateResp.ProtoReflect.Descriptor instead.
func (*TenantUserCreateResp) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{4}
}

func (x *TenantUserCreateResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TenantUserCreateResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TenantUserCreateResp) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *TenantUserCreateResp) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *TenantUserCreateResp) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// delete user request message
type TenantUserDeleteReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant under which this action needs to be taken
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// user id which needs to be deleted
	Username      string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserDeleteReq) Reset() {
	*x = TenantUserDeleteReq{}
	mi := &file_tenant_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserDeleteReq) ProtoMessage() {}

func (x *TenantUserDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserDeleteReq.ProtoReflect.Descriptor instead.
func (*TenantUserDeleteReq) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{5}
}

func (x *TenantUserDeleteReq) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *TenantUserDeleteReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// response to the user delete message
type TenantUserDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserDeleteResp) Reset() {
	*x = TenantUserDeleteResp{}
	mi := &file_tenant_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserDeleteResp) ProtoMessage() {}

func (x *TenantUserDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserDeleteResp.ProtoReflect.Descriptor instead.
func (*TenantUserDeleteResp) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{6}
}

// get user request message
type TenantUserGetReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant under which this action needs to be taken
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// user id which needs to be deleted
	Username      string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserGetReq) Reset() {
	*x = TenantUserGetReq{}
	mi := &file_tenant_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserGetReq) ProtoMessage() {}

func (x *TenantUserGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserGetReq.ProtoReflect.Descriptor instead.
func (*TenantUserGetReq) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{7}
}

func (x *TenantUserGetReq) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *TenantUserGetReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// get user response
type TenantUserGetResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username or user id
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// user email
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// first name of user
	FirstName string `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	// last name of user
	LastName string `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	// is user enabled
	Enabled bool `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// created since
	CreationTimestamp int64 `protobuf:"varint,6,opt,name=creationTimestamp,proto3" json:"creationTimestamp,omitempty"`
	// last access by the user
	LastAccess    int64 `protobuf:"varint,7,opt,name=lastAccess,proto3" json:"lastAccess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserGetResp) Reset() {
	*x = TenantUserGetResp{}
	mi := &file_tenant_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserGetResp) ProtoMessage() {}

func (x *TenantUserGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserGetResp.ProtoReflect.Descriptor instead.
func (*TenantUserGetResp) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{8}
}

func (x *TenantUserGetResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TenantUserGetResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TenantUserGetResp) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *TenantUserGetResp) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *TenantUserGetResp) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TenantUserGetResp) GetCreationTimestamp() int64 {
	if x != nil {
		return x.CreationTimestamp
	}
	return 0
}

func (x *TenantUserGetResp) GetLastAccess() int64 {
	if x != nil {
		return x.LastAccess
	}
	return 0
}

// user update request message
type TenantUserUpdateReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant under which this user will be created
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// user ID
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// email address of the user
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// first name of the user
	Firstname string `protobuf:"bytes,4,opt,name=firstname,proto3" json:"firstname,omitempty"`
	// last name of the user
	Lastname string `protobuf:"bytes,5,opt,name=lastname,proto3" json:"lastname,omitempty"`
	// if the user needs to be created disabled
	Disabled      bool `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserUpdateReq) Reset() {
	*x = TenantUserUpdateReq{}
	mi := &file_tenant_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserUpdateReq) ProtoMessage() {}

func (x *TenantUserUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserUpdateReq.ProtoReflect.Descriptor instead.
func (*TenantUserUpdateReq) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{9}
}

func (x *TenantUserUpdateReq) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *TenantUserUpdateReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TenantUserUpdateReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TenantUserUpdateReq) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *TenantUserUpdateReq) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *TenantUserUpdateReq) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

// response to user update request
type TenantUserUpdateResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username or user id
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// user email
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// first name of user
	FirstName string `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	// last name of user
	LastName string `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	// is user enabled
	Enabled       bool `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserUpdateResp) Reset() {
	*x = TenantUserUpdateResp{}
	mi := &file_tenant_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserUpdateResp) ProtoMessage() {}

func (x *TenantUserUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserUpdateResp.ProtoReflect.Descriptor instead.
func (*TenantUserUpdateResp) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{10}
}

func (x *TenantUserUpdateResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TenantUserUpdateResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TenantUserUpdateResp) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *TenantUserUpdateResp) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *TenantUserUpdateResp) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// enable user request
type TenantUserEnableReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant under consideration
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// user that needs to be enabled
	Username      string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserEnableReq) Reset() {
	*x = TenantUserEnableReq{}
	mi := &file_tenant_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserEnableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserEnableReq) ProtoMessage() {}

func (x *TenantUserEnableReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserEnableReq.ProtoReflect.Descriptor instead.
func (*TenantUserEnableReq) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{11}
}

func (x *TenantUserEnableReq) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *TenantUserEnableReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// enable user request response
type TenantUserEnableResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserEnableResp) Reset() {
	*x = TenantUserEnableResp{}
	mi := &file_tenant_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserEnableResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserEnableResp) ProtoMessage() {}

func (x *TenantUserEnableResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserEnableResp.ProtoReflect.Descriptor instead.
func (*TenantUserEnableResp) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{12}
}

// disable user request
type TenantUserDisableReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant under consideration
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// user that needs to be disabled
	Username      string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserDisableReq) Reset() {
	*x = TenantUserDisableReq{}
	mi := &file_tenant_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserDisableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserDisableReq) ProtoMessage() {}

func (x *TenantUserDisableReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserDisableReq.ProtoReflect.Descriptor instead.
func (*TenantUserDisableReq) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{13}
}

func (x *TenantUserDisableReq) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *TenantUserDisableReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// disable user request response
type TenantUserDisableResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserDisableResp) Reset() {
	*x = TenantUserDisableResp{}
	mi := &file_tenant_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserDisableResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserDisableResp) ProtoMessage() {}

func (x *TenantUserDisableResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserDisableResp.ProtoReflect.Descriptor instead.
func (*TenantUserDisableResp) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{14}
}

// list active sessions request
type TenantUserSessionsListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant under consideration
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// user name to filter for
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// offset to start from
	Offset int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// limit
	Limit         int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserSessionsListReq) Reset() {
	*x = TenantUserSessionsListReq{}
	mi := &file_tenant_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserSessionsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserSessionsListReq) ProtoMessage() {}

func (x *TenantUserSessionsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserSessionsListReq.ProtoReflect.Descriptor instead.
func (*TenantUserSessionsListReq) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{15}
}

func (x *TenantUserSessionsListReq) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *TenantUserSessionsListReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TenantUserSessionsListReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TenantUserSessionsListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// user session information
type TenantUserSessionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user name
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// session id
	SessionId string `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	// start time
	Started int64 `protobuf:"varint,3,opt,name=started,proto3" json:"started,omitempty"`
	// last access time
	LastAccess int64 `protobuf:"varint,4,opt,name=lastAccess,proto3" json:"lastAccess,omitempty"`
	// incoming client ip
	Ip            string `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserSessionInfo) Reset() {
	*x = TenantUserSessionInfo{}
	mi := &file_tenant_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserSessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserSessionInfo) ProtoMessage() {}

func (x *TenantUserSessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserSessionInfo.ProtoReflect.Descriptor instead.
func (*TenantUserSessionInfo) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{16}
}

func (x *TenantUserSessionInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TenantUserSessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TenantUserSessionInfo) GetStarted() int64 {
	if x != nil {
		return x.Started
	}
	return 0
}

func (x *TenantUserSessionInfo) GetLastAccess() int64 {
	if x != nil {
		return x.LastAccess
	}
	return 0
}

func (x *TenantUserSessionInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// response of list active sessions
type TenantUserSessionsListResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total number of active sessions
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// list of active sessions
	Items         []*TenantUserSessionInfo `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserSessionsListResp) Reset() {
	*x = TenantUserSessionsListResp{}
	mi := &file_tenant_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserSessionsListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserSessionsListResp) ProtoMessage() {}

func (x *TenantUserSessionsListResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserSessionsListResp.ProtoReflect.Descriptor instead.
func (*TenantUserSessionsListResp) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{17}
}

func (x *TenantUserSessionsListResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TenantUserSessionsListResp) GetItems() []*TenantUserSessionInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

// user session logout request
type TenantUserSessionLogoutReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant under consideration
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// user to be logged out
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// specific session id if any needs to be logged out
	// optional, if not specified all sessions are logged out
	SessionId     string `protobuf:"bytes,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserSessionLogoutReq) Reset() {
	*x = TenantUserSessionLogoutReq{}
	mi := &file_tenant_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserSessionLogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserSessionLogoutReq) ProtoMessage() {}

func (x *TenantUserSessionLogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserSessionLogoutReq.ProtoReflect.Descriptor instead.
func (*TenantUserSessionLogoutReq) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{18}
}

func (x *TenantUserSessionLogoutReq) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *TenantUserSessionLogoutReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TenantUserSessionLogoutReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// user session logout response
type TenantUserSessionLogoutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserSessionLogoutResp) Reset() {
	*x = TenantUserSessionLogoutResp{}
	mi := &file_tenant_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserSessionLogoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserSessionLogoutResp) ProtoMessage() {}

func (x *TenantUserSessionLogoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserSessionLogoutResp.ProtoReflect.Descriptor instead.
func (*TenantUserSessionLogoutResp) Descriptor() ([]byte, []int) {
	return file_tenant_user_proto_rawDescGZIP(), []int{19}
}

var File_tenant_user_proto protoreflect.FileDescriptor

const file_tenant_user_proto_rawDesc = "" +
	"\n" +
	"\x11tenant-user.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"r\n" +
	"\x12TenantUsersListReq\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"\xe9\x01\n" +
	"\x13TenantUserListEntry\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tfirstName\x18\x03 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x04 \x01(\tR\blastName\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12,\n" +
	"\x11creationTimestamp\x18\x06 \x01(\x03R\x11creationTimestamp\x12\x1e\n" +
	"\n" +
	"lastAccess\x18\a \x01(\x03R\n" +
	"lastAccess\"[\n" +
	"\x13TenantUsersListResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12.\n" +
	"\x05items\x18\x02 \x03(\v2\x18.api.TenantUserListEntryR\x05items\"\xd1\x01\n" +
	"\x13TenantUserCreateReq\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1c\n" +
	"\tfirstname\x18\x04 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x05 \x01(\tR\blastname\x12\x1a\n" +
	"\bdisabled\x18\x06 \x01(\bR\bdisabled\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\"\x9c\x01\n" +
	"\x14TenantUserCreateResp\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tfirstName\x18\x03 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x04 \x01(\tR\blastName\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"I\n" +
	"\x13TenantUserDeleteReq\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x16\n" +
	"\x14TenantUserDeleteResp\"F\n" +
	"\x10TenantUserGetReq\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\xe7\x01\n" +
	"\x11TenantUserGetResp\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tfirstName\x18\x03 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x04 \x01(\tR\blastName\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12,\n" +
	"\x11creationTimestamp\x18\x06 \x01(\x03R\x11creationTimestamp\x12\x1e\n" +
	"\n" +
	"lastAccess\x18\a \x01(\x03R\n" +
	"lastAccess\"\xb5\x01\n" +
	"\x13TenantUserUpdateReq\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1c\n" +
	"\tfirstname\x18\x04 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x05 \x01(\tR\blastname\x12\x1a\n" +
	"\bdisabled\x18\x06 \x01(\bR\bdisabled\"\x9c\x01\n" +
	"\x14TenantUserUpdateResp\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tfirstName\x18\x03 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x04 \x01(\tR\blastName\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"I\n" +
	"\x13TenantUserEnableReq\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x16\n" +
	"\x14TenantUserEnableResp\"J\n" +
	"\x14TenantUserDisableReq\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x17\n" +
	"\x15TenantUserDisableResp\"}\n" +
	"\x19TenantUserSessionsListReq\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x9b\x01\n" +
	"\x15TenantUserSessionInfo\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1c\n" +
	"\tsessionId\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\astarted\x18\x03 \x01(\x03R\astarted\x12\x1e\n" +
	"\n" +
	"lastAccess\x18\x04 \x01(\x03R\n" +
	"lastAccess\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\"d\n" +
	"\x1aTenantUserSessionsListResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x120\n" +
	"\x05items\x18\x02 \x03(\v2\x1a.api.TenantUserSessionInfoR\x05items\"n\n" +
	"\x1aTenantUserSessionLogoutReq\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1c\n" +
	"\tsessionId\x18\x03 \x01(\tR\tsessionId\"\x1d\n" +
	"\x1bTenantUserSessionLogoutResp2\xed\b\n" +
	"\n" +
	"TenantUser\x12i\n" +
	"\bGetUsers\x12\x17.api.TenantUsersListReq\x1a\x18.api.TenantUsersListResp\"*\x82\xd3\xe4\x93\x02$\x12\"/api/auth/v1/tenant/{tenant}/users\x12o\n" +
	"\n" +
	"CreateUser\x12\x18.api.TenantUserCreateReq\x1a\x19.api.TenantUserCreateResp\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/auth/v1/tenant/{tenant}/user\x12n\n" +
	"\aGetUser\x12\x15.api.TenantUserGetReq\x1a\x16.api.TenantUserGetResp\"4\x82\xd3\xe4\x93\x02.\x12,/api/auth/v1/tenant/{tenant}/user/{username}\x12~\n" +
	"\n" +
	"EnableUser\x12\x18.api.TenantUserEnableReq\x1a\x19.api.TenantUserEnableResp\";\x82\xd3\xe4\x93\x025\"3/api/auth/v1/tenant/{tenant}/user/{username}/enable\x12\x82\x01\n" +
	"\vDisableUser\x12\x19.api.TenantUserDisableReq\x1a\x1a.api.TenantUserDisableResp\"<\x82\xd3\xe4\x93\x026\"4/api/auth/v1/tenant/{tenant}/user/{username}/disable\x12w\n" +
	"\n" +
	"UpdateUser\x12\x18.api.TenantUserUpdateReq\x1a\x19.api.TenantUserUpdateResp\"4\x82\xd3\xe4\x93\x02.\x1a,/api/auth/v1/tenant/{tenant}/user/{username}\x12w\n" +
	"\n" +
	"DeleteUser\x12\x18.api.TenantUserDeleteReq\x1a\x19.api.TenantUserDeleteResp\"4\x82\xd3\xe4\x93\x02.*,/api/auth/v1/tenant/{tenant}/user/{username}\x12\x82\x01\n" +
	"\x10ListUserSessions\x12\x1e.api.TenantUserSessionsListReq\x1a\x1f.api.TenantUserSessionsListResp\"-\x82\xd3\xe4\x93\x02'\x12%/api/auth/v1/tenant/{tenant}/sessions\x12\x96\x01\n" +
	"\x11LogoutUserSession\x12\x1f.api.TenantUserSessionLogoutReq\x1a .api.TenantUserSessionLogoutResp\">\x82\xd3\xe4\x93\x028:\x01*\"3/api/auth/v1/tenant/{tenant}/user/{username}/logoutB\x99\x01\x92Aj\x12%\n" +
	"\x1eAuth Gateway API Specification2\x031.0rA\n" +
	"?Auth Gateway API Specification - sample descriptive informationZ*github.com/Prabhjot-Sethi/auth-gateway/apib\x06proto3"

var (
	file_tenant_user_proto_rawDescOnce sync.Once
	file_tenant_user_proto_rawDescData []byte
)

func file_tenant_user_proto_rawDescGZIP() []byte {
	file_tenant_user_proto_rawDescOnce.Do(func() {
		file_tenant_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_user_proto_rawDesc), len(file_tenant_user_proto_rawDesc)))
	})
	return file_tenant_user_proto_rawDescData
}

var file_tenant_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_tenant_user_proto_goTypes = []any{
	(*TenantUsersListReq)(nil),          // 0: api.TenantUsersListReq
	(*TenantUserListEntry)(nil),         // 1: api.TenantUserListEntry
	(*TenantUsersListResp)(nil),         // 2: api.TenantUsersListResp
	(*TenantUserCreateReq)(nil),         // 3: api.TenantUserCreateReq
	(*TenantUserCreateResp)(nil),        // 4: api.TenantUserCreateResp
	(*TenantUserDeleteReq)(nil),         // 5: api.TenantUserDeleteReq
	(*TenantUserDeleteResp)(nil),        // 6: api.TenantUserDeleteResp
	(*TenantUserGetReq)(nil),            // 7: api.TenantUserGetReq
	(*TenantUserGetResp)(nil),           // 8: api.TenantUserGetResp
	(*TenantUserUpdateReq)(nil),         // 9: api.TenantUserUpdateReq
	(*TenantUserUpdateResp)(nil),        // 10: api.TenantUserUpdateResp
	(*TenantUserEnableReq)(nil),         // 11: api.TenantUserEnableReq
	(*TenantUserEnableResp)(nil),        // 12: api.TenantUserEnableResp
	(*TenantUserDisableReq)(nil),        // 13: api.TenantUserDisableReq
	(*TenantUserDisableResp)(nil),       // 14: api.TenantUserDisableResp
	(*TenantUserSessionsListReq)(nil),   // 15: api.TenantUserSessionsListReq
	(*TenantUserSessionInfo)(nil),       // 16: api.TenantUserSessionInfo
	(*TenantUserSessionsListResp)(nil),  // 17: api.TenantUserSessionsListResp
	(*TenantUserSessionLogoutReq)(nil),  // 18: api.TenantUserSessionLogoutReq
	(*TenantUserSessionLogoutResp)(nil), // 19: api.TenantUserSessionLogoutResp
}
var file_tenant_user_proto_depIdxs = []int32{
	1,  // 0: api.TenantUsersListResp.items:type_name -> api.TenantUserListEntry
	16, // 1: api.TenantUserSessionsListResp.items:type_name -> api.TenantUserSessionInfo
	0,  // 2: api.TenantUser.GetUsers:input_type -> api.TenantUsersListReq
	3,  // 3: api.TenantUser.CreateUser:input_type -> api.TenantUserCreateReq
	7,  // 4: api.TenantUser.GetUser:input_type -> api.TenantUserGetReq
	11, // 5: api.TenantUser.EnableUser:input_type -> api.TenantUserEnableReq
	13, // 6: api.TenantUser.DisableUser:input_type -> api.TenantUserDisableReq
	9,  // 7: api.TenantUser.UpdateUser:input_type -> api.TenantUserUpdateReq
	5,  // 8: api.TenantUser.DeleteUser:input_type -> api.TenantUserDeleteReq
	15, // 9: api.TenantUser.ListUserSessions:input_type -> api.TenantUserSessionsListReq
	18, // 10: api.TenantUser.LogoutUserSession:input_type -> api.TenantUserSessionLogoutReq
	2,  // 11: api.TenantUser.GetUsers:output_type -> api.TenantUsersListResp
	4,  // 12: api.TenantUser.CreateUser:output_type -> api.TenantUserCreateResp
	8,  // 13: api.TenantUser.GetUser:output_type -> api.TenantUserGetResp
	12, // 14: api.TenantUser.EnableUser:output_type -> api.TenantUserEnableResp
	14, // 15: api.TenantUser.DisableUser:output_type -> api.TenantUserDisableResp
	10, // 16: api.TenantUser.UpdateUser:output_type -> api.TenantUserUpdateResp
	6,  // 17: api.TenantUser.DeleteUser:output_type -> api.TenantUserDeleteResp
	17, // 18: api.TenantUser.ListUserSessions:output_type -> api.TenantUserSessionsListResp
	19, // 19: api.TenantUser.LogoutUserSession:output_type -> api.TenantUserSessionLogoutResp
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_tenant_user_proto_init() }
func file_tenant_user_proto_init() {
	if File_tenant_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_user_proto_rawDesc), len(file_tenant_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenant_user_proto_goTypes,
		DependencyIndexes: file_tenant_user_proto_depIdxs,
		MessageInfos:      file_tenant_user_proto_msgTypes,
	}.Build()
	File_tenant_user_proto = out.File
	file_tenant_user_proto_goTypes = nil
	file_tenant_user_proto_depIdxs = nil
}
