// Code generated by protoc-gen-routes. DO NOT EDIT.
// source: tenant-user.proto

package api

import "github.com/go-core-stack/auth/model"

var RoutesTenantUser = []*model.Route{}

func init() {

	RoutesTenantUser = append(RoutesTenantUser, model.NewRoute("/api/auth/v1/tenant/{tenant}/users", "GET"))

	RoutesTenantUser = append(RoutesTenantUser, model.NewRoute("/api/auth/v1/tenant/{tenant}/user", "POST"))

	RoutesTenantUser = append(RoutesTenantUser, model.NewRoute("/api/auth/v1/tenant/{tenant}/user/{username}", "GET"))

	RoutesTenantUser = append(RoutesTenantUser, model.NewRoute("/api/auth/v1/tenant/{tenant}/user/{username}/enable", "POST"))

	RoutesTenantUser = append(RoutesTenantUser, model.NewRoute("/api/auth/v1/tenant/{tenant}/user/{username}/disable", "POST"))

	RoutesTenantUser = append(RoutesTenantUser, model.NewRoute("/api/auth/v1/tenant/{tenant}/user/{username}", "PUT"))

	RoutesTenantUser = append(RoutesTenantUser, model.NewRoute("/api/auth/v1/tenant/{tenant}/user/{username}", "DELETE"))

	RoutesTenantUser = append(RoutesTenantUser, model.NewRoute("/api/auth/v1/tenant/{tenant}/sessions", "GET"))

	RoutesTenantUser = append(RoutesTenantUser, model.NewRoute("/api/auth/v1/tenant/{tenant}/user/{username}/logout", "POST"))

}
