// Code generated by protoc-gen-routes. DO NOT EDIT.
// source: tenant.proto

package api

import "github.com/go-core-stack/auth/model"

var RoutesTenant = []*model.Route{}

func init() {
	var route *model.Route

	// Adding Route information for ListTenants RPC
	route = model.NewRoute("/api/auth/v1/tenants", "GET")
	route.Resource = "tenant"
	route.Verb = "list"
	RoutesTenant = append(RoutesTenant, route)

	// Adding Route information for CreateTenant RPC
	route = model.NewRoute("/api/auth/v1/tenant", "POST")
	route.Resource = "tenant"
	route.Verb = "create"
	RoutesTenant = append(RoutesTenant, route)

	// Adding Route information for GetTenant RPC
	route = model.NewRoute("/api/auth/v1/tenant/{id}", "GET")
	route.Resource = "tenant"
	route.Verb = "get"
	RoutesTenant = append(RoutesTenant, route)
}
